# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retroAPI', '0001_organization_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='teams',
            field=models.ManyToManyField(null=True, related_name='organization_teams', to='retroAPI.Team'),
        ),
    ]
