# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retroAPI', '0003_auto_20171222_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='retro',
            name='descritpion',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
