# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retroAPI', '0004_retro_descritpion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retro',
            old_name='descritpion',
            new_name='description',
        ),
    ]
