# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retroAPI', '0002_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
