# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retroAPI', '0003_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='retroitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retroAPI.Category'),
        ),
    ]
